# Generated by Django 5.2.5 on 2026-01-28 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerMonthDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('timezone', models.CharField(default='Asia/Jakarta', max_length=50)),
                ('source_hash', models.CharField(max_length=64)),
                ('last_updated', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='main_prayer_user_id_55423f_idx'), models.Index(fields=['year', 'month'], name='main_prayer_year_441261_idx')],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
