# Generated by Django 5.2.5 on 2026-01-28 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_prayermonthdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrayerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subuh', models.BooleanField(default=True)),
                ('dzuhur', models.BooleanField(default=True)),
                ('ashar', models.BooleanField(default=True)),
                ('maghrib', models.BooleanField(default=True)),
                ('isya', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
