# Generated by Django 5.2.5 on 2026-01-29 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprayerpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prayer_name', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_log',
            },
        ),
        migrations.RenameIndex(
            model_name='prayermonthdocument',
            new_name='jadwal_shal_user_id_a6251d_idx',
            old_name='main_prayer_user_id_55423f_idx',
        ),
        migrations.RenameIndex(
            model_name='prayermonthdocument',
            new_name='jadwal_shal_year_2b1df6_idx',
            old_name='main_prayer_year_441261_idx',
        ),
        migrations.AlterModelTable(
            name='prayermonthdocument',
            table='jadwal_shalat_data',
        ),
        migrations.AlterModelTable(
            name='userprayerpreference',
            table='notification_preference',
        ),
        migrations.AddField(
            model_name='prayernotificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='prayernotificationlog',
            unique_together={('user', 'date', 'prayer_name')},
        ),
    ]
