# Generated by Django 5.2.5 on 2026-03-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_prayernotificationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='foto_profil'),
        ),
    ]
