# Generated by Django 5.2.5 on 2026-05-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_feed_feedcomment_feedpicture_story_feedlike_follow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_headline', models.BooleanField(default=False)),
                ('is_recommendation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lifestyle_fest',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['category'], name='lifestyle_f_categor_7c31fc_idx'), models.Index(fields=['date'], name='lifestyle_f_date_7842d0_idx'), models.Index(fields=['is_headline'], name='lifestyle_f_is_head_efdefa_idx'), models.Index(fields=['is_recommendation'], name='lifestyle_f_is_reco_f31351_idx')],
            },
        ),
    ]
