# Generated by Django 5.2.5 on 2026-05-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_fest'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fest',
            name='lifestyle_f_categor_7c31fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='fest',
            name='lifestyle_f_date_7842d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='fest',
            name='lifestyle_f_is_head_efdefa_idx',
        ),
        migrations.RemoveIndex(
            model_name='fest',
            name='lifestyle_f_is_reco_f31351_idx',
        ),
        migrations.AlterField(
            model_name='fest',
            name='banner',
            field=models.ImageField(max_length=500, upload_to='fest_banners/'),
        ),
    ]
