# Generated by Django 5.2.5 on 2026-05-22 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_fest_lifestyle_f_categor_7c31fc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasjidReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_id', models.CharField(db_index=True, max_length=255)),
                ('rating', models.IntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masjid_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'masjid_review',
            },
        ),
        migrations.CreateModel(
            name='MasjidReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='masjid_reviews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.masjidreview')),
            ],
            options={
                'db_table': 'masjid_review_photo',
            },
        ),
        migrations.AddIndex(
            model_name='masjidreview',
            index=models.Index(fields=['place_id'], name='masjid_revi_place_i_6ee281_idx'),
        ),
        migrations.AddIndex(
            model_name='masjidreview',
            index=models.Index(fields=['-created_at'], name='masjid_revi_created_eabd5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='masjidreview',
            unique_together={('user', 'place_id')},
        ),
    ]
