# Generated by Django 5.2.5 on 2026-05-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_klinikreview_klinikreviewphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klinikreview',
            name='place_id',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
