# Generated by Django 5.2.5 on 2026-05-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_klinikreview_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klinikreview',
            name='place_id',
            field=models.TextField(db_index=True),
        ),
    ]
