# Generated by Django 5.2.5 on 2026-05-26 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_klinikreview_place_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('step', models.IntegerField()),
                ('arabic_text_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('is_finished', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ngaji_detail_pelajaran',
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='KelasTahfidz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_in_seconds', models.IntegerField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='kelas_banners/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_dewasa', models.BooleanField(default=True)),
                ('lecturer_id', models.IntegerField()),
                ('lecturer_name', models.CharField(max_length=255)),
                ('enroll_count', models.IntegerField(default=0)),
                ('learning_materials', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ngaji_kelas_tahfidz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('step', models.IntegerField(default=1)),
                ('course_total', models.IntegerField(default=0)),
                ('course_finished', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ngaji_pelajaran',
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='KelasSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.JSONField(default=list)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_in_seconds', models.IntegerField()),
                ('enrolled_students', models.IntegerField(default=0)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.kelastahfidz')),
            ],
            options={
                'db_table': 'ngaji_kelas_schedule',
            },
        ),
        migrations.CreateModel(
            name='MateriPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('arabic', models.CharField(max_length=50)),
                ('latin', models.CharField(max_length=50)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('detail_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi', to='main.detailpelajaran')),
            ],
            options={
                'db_table': 'ngaji_materi_pelajaran',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='detailpelajaran',
            name='pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='main.pelajaran'),
        ),
        migrations.CreateModel(
            name='KelasEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_enrollments', to=settings.AUTH_USER_MODEL)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main.kelastahfidz')),
            ],
            options={
                'db_table': 'ngaji_kelas_enrollment',
                'unique_together': {('user', 'kelas')},
            },
        ),
    ]
