# Generated by Django 5.2.5 on 2026-05-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_detailpelajaran_kelastahfidz_pelajaran_kelasschedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpicture',
            name='feed',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='caption',
            new_name='feed_caption',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='location',
            new_name='feed_location',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='is_sponsored',
            new_name='isSponsored',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='media_url',
            new_name='story_link',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='story',
            name='media_type',
        ),
        migrations.AddField(
            model_name='feed',
            name='feed_pictures',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='feed',
            name='user_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='isOnline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='user_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['user', '-created_at'], name='social_feed_user_id_2eb3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['-created_at'], name='social_feed_created_b863d5_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['user_country'], name='social_feed_user_co_801d29_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['isSponsored'], name='social_feed_isSpons_1e6b51_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['user', '-created_at'], name='social_stor_user_id_09a55d_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['user_country'], name='social_stor_user_co_66e548_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['expires_at'], name='social_stor_expires_2883fe_idx'),
        ),
        migrations.DeleteModel(
            name='FeedPicture',
        ),
    ]
