# Generated by Django 5.2.5 on 2026-05-29 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_user_email_verification_token_user_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KisahNabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prophet_name', models.CharField(max_length=100)),
                ('total_read_count', models.IntegerField(default=0)),
                ('main_cover', models.ImageField(blank=True, null=True, upload_to='kisah_nabi/covers/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kisah_nabi',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='KisahNabiEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('doc_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kisah_nabi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='main.kisahnabi')),
            ],
            options={
                'db_table': 'kisah_nabi_episode',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KisahNabiReadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_logs', to='main.kisahnabiepisode')),
                ('kisah_nabi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_logs', to='main.kisahnabi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kisah_read_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kisah_nabi_read_log',
            },
        ),
    ]
