# Generated by Django 5.2.5 on 2026-05-31 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TilawahAyahPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.IntegerField()),
                ('surah_name', models.CharField(max_length=100)),
                ('ayah_number', models.IntegerField()),
                ('ayah_text', models.TextField()),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'unique_together': {('surah_number', 'ayah_number')},
            },
        ),
        migrations.CreateModel(
            name='TilawahSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.IntegerField()),
                ('surah_name', models.CharField(max_length=100)),
                ('ayah_number', models.IntegerField()),
                ('ayah_text', models.TextField()),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20)),
                ('tajwid_score', models.FloatField(blank=True, null=True)),
                ('word_accuracy', models.FloatField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tilawah_audio/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('feedback_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
