# Generated by Django 5.2.5 on 2026-06-11 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_tilawahayahpool_tilawahsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelasenrollment',
            old_name='is_active',
            new_name='is_dewasa',
        ),
        migrations.AddField(
            model_name='kelasenrollment',
            name='address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kelasenrollment',
            name='enrollment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='kelasenrollment',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kelasenrollment',
            name='jenis_kelamin',
            field=models.CharField(choices=[('laki-laki', 'Laki-laki'), ('perempuan', 'Perempuan')], default='laki-laki', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kelasenrollment',
            name='nama_lengkap',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kelasenrollment',
            name='ngaji_level',
            field=models.IntegerField(default=0, help_text='1=Beginner, 2=Basic, 3=Intermediate, 4=Advanced'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kelasenrollment',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kelasenrollment',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kelasenrollment',
            name='selected_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='main.kelasschedule'),
        ),
        migrations.AddField(
            model_name='kelasenrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kelasenrollment',
            name='usia_in_tahun',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
