# Generated by Django 5.2.5 on 2026-06-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_is_active_kelasenrollment_is_dewasa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilawahayahpool',
            name='ayah_text_modern',
            field=models.TextField(blank=True, null=True),
        ),
    ]
