# Generated by Django 5.2.5 on 2026-06-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_tilawahayahpool_ayah_text_modern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tilawahayahpool',
            old_name='ayah_text_modern',
            new_name='ayah_translation',
        ),
        migrations.AddField(
            model_name='tilawahayahpool',
            name='ayah_transliteration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
