# Generated by Django 5.2.5 on 2026-06-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_ayah_text_modern_tilawahayahpool_ayah_translation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tilawahayahpool',
            options={'ordering': ['surah_number', 'ayah_number']},
        ),
        migrations.AddField(
            model_name='tilawahayahpool',
            name='juz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tilawahayahpool',
            name='surah_name_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tilawahayahpool',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tilawahayahpool',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='basic', max_length=20),
        ),
        migrations.AlterModelTable(
            name='tilawahayahpool',
            table='tilawah_ayah_pool',
        ),
    ]
