# Generated by Django 5.2.5 on 2026-06-22 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_tilawahayahpool_options_tilawahayahpool_juz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('level', models.CharField(default='starter', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_user_level',
            },
        ),
        migrations.CreateModel(
            name='AmalanCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amalan', models.CharField(choices=[('tilawah', 'Tilawah'), ('dzikir', 'Dzikir'), ('puasa_sunnah', 'Puasa Sunnah'), ('sedekah', 'Sedekah'), ('tahajjud', 'Tahajjud'), ('dhuha', 'Dhuha'), ('kajian', 'Kajian')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amalan_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_amalan_checkin',
                'ordering': ['-date'],
                'unique_together': {('user', 'amalan', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amalan', models.CharField(choices=[('shalat', 'Shalat'), ('tilawah', 'Tilawah'), ('dzikir', 'Dzikir'), ('puasa_sunnah', 'Puasa Sunnah'), ('sedekah', 'Sedekah'), ('tahajjud', 'Tahajjud'), ('dhuha', 'Dhuha'), ('kajian', 'Kajian')], max_length=20)),
                ('streak_count', models.IntegerField(default=0)),
                ('last_check_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_user_streak',
                'unique_together': {('user', 'amalan')},
            },
        ),
    ]
