# Generated by Django 5.2.5 on 2026-07-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_userlevel_amalancheckin_userstreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10, null=True),
        ),
    ]
