# Generated by Django 5.2.5 on 2026-07-02 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_user_jenis_kelamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_in_feeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
