# Generated by Django 5.2.5 on 2026-07-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_feed_tagged_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, help_text='User profile banner with 12:5 aspect ratio (landscape)', null=True, upload_to='user_banners/'),
        ),
    ]
