# Generated by Django 5.2.5 on 2026-07-02 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_user_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.feedcomment'),
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
