# Generated by Django 5.2.5 on 2026-07-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
