# Generated by Django 5.2.5 on 2026-07-04 01:36

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_feed_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitabHadis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=50, unique=True)),
                ('nama_indonesia', models.CharField(max_length=100)),
                ('jumlah_hadis', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'hadis_kitab',
                'ordering': ['nama_indonesia'],
            },
        ),
        migrations.CreateModel(
            name='Hadis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField()),
                ('teks_arab', models.TextField()),
                ('terjemahan', models.TextField()),
                ('teks_hadis', models.TextField()),
                ('isi_hadis', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('kitab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadis', to='main.kitabhadis')),
            ],
            options={
                'db_table': 'hadis',
                'ordering': ['kitab', 'nomor'],
                'indexes': [models.Index(fields=['kitab', 'nomor'], name='hadis_kitab_i_f0aa15_idx')],
                'unique_together': {('kitab', 'nomor')},
            },
        ),
    ]
