# Generated by Django 5.2.5 on 2026-07-04 01:54

from django.db import migrations
from django.contrib.postgres.search import SearchVector

def update_search_vector(apps, schema_editor):
    Hadis = apps.get_model('main', 'Hadis')
    Hadis.objects.update(
        search_vector=(
            SearchVector('teks_hadis', weight='A') +
            SearchVector('isi_hadis', weight='B') +
            SearchVector('terjemahan', weight='C')
        )
    )

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_kitabhadis_hadis'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS hadis_search_vector_idx 
            ON hadis USING GIN (search_vector);
            """
        ),
        migrations.RunPython(update_search_vector),
    ]
