# Generated by Django 5.2.5 on 2026-07-05 01:29
from pgvector.django import VectorExtension
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20260704_0854'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='hadis',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
