# Generated by Django 5.2.5 on 2026-07-05 07:15

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_hadis_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadis',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
