# Generated by Django 5.2.5 on 2026-07-05 11:00

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_hadis_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilawahayahpool',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
