# Generated by Django 5.2.5 on 2026-07-09 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_tilawahayahpool_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuntunanShalat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TuntunanShalatPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('page_title', models.CharField(max_length=255)),
                ('blocks', models.JSONField(default=list)),
                ('tuntunan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='main.tuntunanshalat')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('tuntunan', 'page_number')},
            },
        ),
    ]
