# Generated by Django 5.2.5 on 2026-07-09 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_tuntunanshalat_tuntunanshalatpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Doa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('page_title', models.CharField(max_length=255)),
                ('hero_image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doas', to='main.doacategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DoaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('sub_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('arabic_text', models.TextField()),
                ('transliteration', models.TextField(blank=True, null=True)),
                ('translation', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('doa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='main.doa')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DoaBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='main.doa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doa_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'doa')},
            },
        ),
    ]
