# Generated by Django 5.2.5 on 2026-07-09 02:14

import main.models_tuntunan_shalat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_doacategory_doa_doacontent_doabookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuntunanShalatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='tuntunan_shalat/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doa',
            name='hero_image_url',
        ),
        migrations.AddField(
            model_name='doa',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='doa/hero_images/'),
        ),
        migrations.AlterField(
            model_name='tuntunanshalatpage',
            name='blocks',
            field=models.JSONField(default=list, validators=[main.models_tuntunan_shalat.validate_tuntunan_blocks]),
        ),
    ]
