# Generated by Django 5.2.5 on 2026-07-09 02:21

import main.models_tuntunan_shalat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_tuntunanshalatimage_remove_doa_hero_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doa',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Doa', 'verbose_name_plural': 'Doa'},
        ),
        migrations.AlterModelOptions(
            name='doabookmark',
            options={'verbose_name': 'Doa Bookmark', 'verbose_name_plural': 'Doa Bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='doacategory',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Doa Category', 'verbose_name_plural': 'Doa Categories'},
        ),
        migrations.AlterModelOptions(
            name='doacontent',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Doa Content', 'verbose_name_plural': 'Doa Contents'},
        ),
        migrations.AlterModelOptions(
            name='tuntunanshalat',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Tuntunan Shalat', 'verbose_name_plural': 'Tuntunan Shalat'},
        ),
        migrations.AlterModelOptions(
            name='tuntunanshalatimage',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'Tuntunan Shalat Image', 'verbose_name_plural': 'Tuntunan Shalat Images'},
        ),
        migrations.AlterModelOptions(
            name='tuntunanshalatpage',
            options={'ordering': ['page_number', 'id'], 'verbose_name': 'Tuntunan Shalat Page', 'verbose_name_plural': 'Tuntunan Shalat Pages'},
        ),
        migrations.AlterField(
            model_name='tuntunanshalatpage',
            name='blocks',
            field=models.JSONField(default=list, help_text='Array of content blocks: heading, paragraph, arabic, transliteration, translation, step, surah, image.', validators=[main.models_tuntunan_shalat.validate_tuntunan_blocks]),
        ),
    ]
