# Generated by Django 5.2.5 on 2026-07-09 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_doa_options_alter_doabookmark_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuntunanShalatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('arabic', 'Arabic'), ('transliteration', 'Transliteration'), ('translation', 'Translation'), ('step', 'Step'), ('surah', 'Surah'), ('image', 'Image')], max_length=32)),
                ('text', models.TextField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tuntunan_shalat/block_images/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ayah_count', models.PositiveIntegerField(blank=True, null=True)),
                ('arabic_header', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tuntunan Shalat Block',
                'verbose_name_plural': 'Tuntunan Shalat Blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='TuntunanShalatImage',
        ),
        migrations.RemoveField(
            model_name='tuntunanshalatpage',
            name='blocks',
        ),
        migrations.AddField(
            model_name='tuntunanshalatblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.tuntunanshalatpage'),
        ),
    ]
