# Generated by Django 5.2.5 on 2026-07-09 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_tuntunanshalatpage_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='healthy_tips/')),
                ('description_short', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('article', models.TextField(help_text='Isi artikel dalam format Markdown.')),
                ('section', models.CharField(choices=[('tips_baru', 'Tips Baru'), ('seminar_sehat', 'Seminar Sehat'), ('general', 'General')], db_index=True, default='general', max_length=30)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthy_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'healthy_tips',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['section', '-created_at'], name='healthy_tip_section_b246ee_idx'), models.Index(fields=['is_published', '-created_at'], name='healthy_tip_is_publ_72757f_idx')],
            },
        ),
    ]
