# Generated by Django 5.2.5 on 2026-07-09 08:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_healthytip'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Category',
                'verbose_name_plural': 'Media Categories',
                'db_table': 'media_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArtikelIslami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='media_islami/articles/banners/')),
                ('description', models.TextField(blank=True, null=True)),
                ('article', models.TextField(help_text='Isi artikel dalam format Markdown.')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_artikel_islami', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artikel_islami', to='main.mediacategory')),
            ],
            options={
                'db_table': 'artikel_islami',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='artikel_isl_is_publ_6093e2_idx'), models.Index(fields=['category', '-created_at'], name='artikel_isl_categor_72b660_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShortIslami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media_islami/shorts/thumbnails/')),
                ('video', models.FileField(upload_to='media_islami/shorts/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm'])])),
                ('description', models.TextField(blank=True, null=True)),
                ('view_count', models.BigIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shorts', to='main.mediacategory')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_shorts_islami', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'short_islami',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='short_islam_is_publ_c7d851_idx'), models.Index(fields=['category', '-created_at'], name='short_islam_categor_99cd49_idx'), models.Index(fields=['view_count'], name='short_islam_view_co_7a81c6_idx')],
            },
        ),
    ]
