# Generated by Django 5.2.5 on 2026-07-09 09:00

import django.core.validators
import main.utils_media_islami.file_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_mediacategory_artikelislami_shortislami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortislami',
            name='video',
            field=models.FileField(upload_to='media_islami/shorts/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm']), main.utils_media_islami.file_validator.validate_video_size]),
        ),
    ]
