# Generated by Django 5.2.5 on 2026-07-09 10:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_shortislami_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book Author',
                'verbose_name_plural': 'Book Authors',
                'db_table': 'book_authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book Category',
                'verbose_name_plural': 'Book Categories',
                'db_table': 'book_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IslamicBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='e_pustaka/covers/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('publish_year', models.PositiveIntegerField(db_index=True)),
                ('sold_count', models.BigIntegerField(db_index=True, default=0)),
                ('synopsis', models.TextField()),
                ('pdf', models.FileField(upload_to='e_pustaka/books/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('is_recommended', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='main.bookauthor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='main.bookcategory')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'islamic_books',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='islamic_boo_is_publ_003fc1_idx'), models.Index(fields=['category', '-created_at'], name='islamic_boo_categor_1732b6_idx'), models.Index(fields=['author'], name='islamic_boo_author__3a2bc2_idx'), models.Index(fields=['is_recommended'], name='islamic_boo_is_reco_275fe1_idx'), models.Index(fields=['sold_count'], name='islamic_boo_sold_co_c28fa4_idx')],
            },
        ),
    ]
