# Generated by Django 5.2.5 on 2026-07-09 11:20

import django.core.validators
import main.utils_epustaka.file_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_bookauthor_bookcategory_islamicbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicbook',
            name='pdf',
            field=models.FileField(upload_to='e_pustaka/books/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), main.utils_epustaka.file_validator.validate_pdf_size]),
        ),
    ]
