# Generated by Django 5.2.5 on 2026-07-16 23:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_islamicbook_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='TilawahAyahTajwidAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_index', models.PositiveIntegerField()),
                ('next_word_index', models.PositiveIntegerField(blank=True, null=True)),
                ('start_grapheme', models.PositiveIntegerField()),
                ('end_grapheme', models.PositiveIntegerField()),
                ('start_codepoint', models.PositiveIntegerField()),
                ('end_codepoint', models.PositiveIntegerField()),
                ('arabic_segment', models.TextField()),
                ('applies_when', models.CharField(choices=[('wasl', 'Wasal'), ('waqf', 'Waqaf'), ('both', 'Keduanya')], max_length=8)),
                ('expected_features', models.JSONField(blank=True, default=dict)),
                ('locator_confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('locator_method', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tilawah_ayah_tajwid_annotation',
                'ordering': ['annotation_set_id', 'start_grapheme', 'end_grapheme', 'rule_id'],
            },
        ),
        migrations.CreateModel(
            name='TilawahAyahTajwidAnnotationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_version', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Versi engine mengandung karakter yang tidak valid.', regex='^[A-Za-z0-9._+-]+$')])),
                ('reading_mode', models.CharField(choices=[('ayah', 'Tampilan Ayat'), ('wasl', 'Wasal'), ('waqf', 'Waqaf')], default='ayah', max_length=8)),
                ('source_text_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='source_text_hash harus berupa SHA-256 lowercase sepanjang 64 karakter.', regex='^[0-9a-f]{64}$')])),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('validated', 'Validated Otomatis'), ('needs_review', 'Perlu Review'), ('verified', 'Terverifikasi Ahli'), ('published', 'Published'), ('failed', 'Failed')], default='generated', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('is_safe_to_persist', models.BooleanField(default=False)),
                ('annotation_count', models.PositiveIntegerField(default=0)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tilawah_ayah_tajwid_annotation_set',
                'ordering': ['ayah_id', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TilawahTajwidRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Kode hukum hanya boleh berisi huruf kecil, angka, dan underscore.', regex='^[a-z0-9_]+$')])),
                ('name', models.CharField(max_length=100)),
                ('display_group', models.CharField(choices=[('nun_tanwin', 'Nun Mati dan Tanwin'), ('mim_sakinah', 'Mim Sakinah'), ('mad', 'Mad'), ('qalqalah', 'Qalqalah'), ('ghunnah', 'Ghunnah'), ('alif_lam', 'Alif Lam'), ('idgham', 'Idgham'), ('tafkhim_tarqiq', 'Tafkhim dan Tarqiq'), ('waqf', 'Waqaf')], max_length=32)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Warna harus menggunakan format Flutter 0xFFAABBCC.', regex='^0xFF[0-9A-F]{6}$')])),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('default_applies_when', models.CharField(choices=[('wasl', 'Wasal'), ('waqf', 'Waqaf'), ('both', 'Keduanya'), ('contextual', 'Kontekstual')], max_length=16)),
                ('assessment_family', models.CharField(choices=[('articulation', 'Artikulasi'), ('assimilation', 'Asimilasi'), ('nasalization', 'Dengung'), ('duration', 'Durasi'), ('release', 'Pelepasan Bunyi'), ('resonance', 'Resonansi'), ('pause', 'Jeda'), ('render_only', 'Tampilan Saja')], max_length=24)),
                ('supported_levels', models.JSONField(default=list)),
                ('expected_features', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tilawah_tajwid_rule',
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.AddField(
            model_name='tilawahayahpool',
            name='level_engine_version',
            field=models.CharField(blank=True, default='', max_length=32, validators=[django.core.validators.RegexValidator(message='Versi engine mengandung karakter yang tidak valid.', regex='^[A-Za-z0-9._+-]+$')]),
        ),
        migrations.AddField(
            model_name='tilawahayahpool',
            name='level_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tilawahayahpool',
            name='level_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tilawahayahpool',
            name='level_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tilawahayahpool',
            name='level_source',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('engine', 'Engine'), ('manual', 'Manual')], default='legacy', max_length=16),
        ),
        migrations.AddField(
            model_name='tilawahayahpool',
            name='level_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tilawahayahpool',
            index=models.Index(fields=['level', 'surah_number'], name='idx_tilawah_level_surah'),
        ),
        migrations.AddConstraint(
            model_name='tilawahayahpool',
            constraint=models.CheckConstraint(condition=models.Q(('surah_number__gte', 1), ('surah_number__lte', 114)), name='ck_tilawah_ayah_surah_range'),
        ),
        migrations.AddConstraint(
            model_name='tilawahayahpool',
            constraint=models.CheckConstraint(condition=models.Q(('ayah_number__gte', 1)), name='ck_tilawah_ayah_number_positive'),
        ),
        migrations.AddField(
            model_name='tilawahayahtajwidannotationset',
            name='ayah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tajwid_annotation_sets', to='main.tilawahayahpool'),
        ),
        migrations.AddField(
            model_name='tilawahayahtajwidannotationset',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tajwid_annotation_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tilawahayahtajwidannotation',
            name='annotation_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='main.tilawahayahtajwidannotationset'),
        ),
        migrations.AddIndex(
            model_name='tilawahtajwidrule',
            index=models.Index(fields=['display_group', 'is_active'], name='idx_tajwid_rule_group_active'),
        ),
        migrations.AddField(
            model_name='tilawahayahtajwidannotation',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ayah_annotations', to='main.tilawahtajwidrule'),
        ),
        migrations.AddIndex(
            model_name='tilawahayahtajwidannotationset',
            index=models.Index(fields=['ayah', 'reading_mode', 'is_active'], name='idx_taj_set_ayah_mode_act'),
        ),
        migrations.AddIndex(
            model_name='tilawahayahtajwidannotationset',
            index=models.Index(fields=['status', 'engine_version'], name='idx_tajwid_set_status_engine'),
        ),
        migrations.AddConstraint(
            model_name='tilawahayahtajwidannotationset',
            constraint=models.UniqueConstraint(fields=('ayah', 'engine_version', 'source_text_hash', 'reading_mode'), name='uq_tajwid_set_ayah_engine_hash_mode'),
        ),
        migrations.AddConstraint(
            model_name='tilawahayahtajwidannotationset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('ayah', 'reading_mode'), name='uq_tajwid_set_one_active_per_mode'),
        ),
        migrations.AddConstraint(
            model_name='tilawahayahtajwidannotationset',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), ('status', 'published'), _connector='OR'), name='ck_tajwid_set_active_must_published'),
        ),
        migrations.AddIndex(
            model_name='tilawahayahtajwidannotation',
            index=models.Index(fields=['annotation_set', 'start_grapheme'], name='idx_taj_ann_set_start'),
        ),
        migrations.AddIndex(
            model_name='tilawahayahtajwidannotation',
            index=models.Index(fields=['rule', 'is_verified'], name='idx_taj_ann_rule_verified'),
        ),
        migrations.AddConstraint(
            model_name='tilawahayahtajwidannotation',
            constraint=models.UniqueConstraint(fields=('annotation_set', 'rule', 'start_grapheme', 'end_grapheme', 'applies_when'), name='uq_tajwid_annotation_set_rule_span_mode'),
        ),
        migrations.AddConstraint(
            model_name='tilawahayahtajwidannotation',
            constraint=models.CheckConstraint(condition=models.Q(('end_grapheme__gt', models.F('start_grapheme'))), name='ck_tajwid_annotation_grapheme_range'),
        ),
        migrations.AddConstraint(
            model_name='tilawahayahtajwidannotation',
            constraint=models.CheckConstraint(condition=models.Q(('end_codepoint__gt', models.F('start_codepoint'))), name='ck_tajwid_annotation_codepoint_range'),
        ),
        migrations.AddConstraint(
            model_name='tilawahayahtajwidannotation',
            constraint=models.CheckConstraint(condition=models.Q(('locator_confidence__gte', 0), ('locator_confidence__lte', 1)), name='ck_tajwid_annotation_confidence'),
        ),
        migrations.AddConstraint(
            model_name='tilawahayahtajwidannotation',
            constraint=models.CheckConstraint(condition=models.Q(('next_word_index__isnull', True), ('next_word_index__gt', models.F('word_index')), _connector='OR'), name='ck_tajwid_annotation_next_word'),
        ),
    ]
